### ISSUE TITLE
where to get `mhlo_tools` module

### ISSUE THREAD

**Issue by gglin001** [bytedance/byteir#18]
hi, I found some tests are using `mhlo_tools` 
eg: https://github.com/bytedance/byteir/blob/main/compiler/numerical/hlo/numerical_test.py#L2

how to get the `mhlo_tools` ?

**Comment by liwenchangbdbz** [comment]
The mhlo_tools is used for golden numerical reference on top of existing mhlo with python binding.
We only used it in CI, and due to some potential copyright issues we couldn't put it in the public repo.
We might make it public if the copyright issues are resolved, or can reroute it to another repo if there is an official version in mhlo/stablehlo.

**Comment by gglin001** [comment]
got it. thanks
