### ISSUE TITLE
[QUESTION] Why does ByteIR define Softmax as a structured Op, while the original Softmax does not

### ISSUE THREAD

**Issue by PineWu** [bytedance/byteir#389]
As tilted:
- ByteIR defines Linalg_ext.Softmax as a structured Op;
- But the MLIR  Linalg.Softmax does not?

**Comment by liwenchangbdbz** [comment]
Short answer:
ByteIR's Linalg_ext.Softmax is inherited from ByteIR's structured Op, not MLIR's structured Op.
Structured Op basically is a way to allow ops to share some properties (eventually able to apply same member functions).
ByteIR extended several ops, including Softmax, TopK, and Sort, through ByteIR's structured Op. 
Upstream MLIR didn't apply that and make Softmax the only special op, so there is no need to create a new level abstraction.  

Long answer:
The upstream Linalg.Softmax was actually inspired by ByteIR's Linalg_ext.Softmax.
However, for some reasons, upstream Linalg.Softmax still only support parallel tiling, no reduction tiling. 
With only parallel tiling, there is no need to create any abstraction. 
ByteIR's Linalg_ext.Softmax supports reduction tiling as well, in order to generate something like parallel softmax and FlashAttention. 
ByteIR's  structured Op is created to support reduction tiling in those special ops (softmax, topk, and sort).
