### ISSUE TITLE
[QUESTION] About Conversion MLIR Mesh dialect to Ccl ops

### ISSUE THREAD

**Issue by alphaRGB** [bytedance/byteir#458]
I found that **Ccl dialect** exists in this project to represent collective communication. But I have not found which dialalct will be lowered to Ccl dialect.
* Is there any example to demonstrate the usage of Ccl ops ?
* MLIR upstream Mesh dialect will be lowered to Ccl dialect, is there any plan ?  

Thank you very much ~

**Comment by liwenchangbdbz** [comment]
If you use the ByteIR runtime, there is NCCL backend for the nvidia GPUs. 
If you use other runtime or other hardware, you can lower ccl dialect to communication libraries based on the op semantics. 

Mesh dialect in MLIR upstream is actually contributed by the ByteIR team. 
Meah dialect uses semantics of virtual or physical mesh network topology, which is often used in distributed training/inference for easy abstraction, while ccl dialect use physical rank to practically performs the real communication operations.   
We originally introduce mesh dialect for supporting TF and pytorch training framework.
However, due the current training framework shifts more to pytoch, and pytorch natively lacks some support of mesh and distributed abstraction at the moment we released mesh dialect, the ByteIR team decided to extend PyTorch ecosystem first in order to link mesh to pytorch later and make the ecosystem more practical.
The extension we built is called veScale, you can find in this link https://github.com/volcengine/vescale . 
At the current stage, we haven't release the veScale version that can link ByteIR yet, but we will.

**Comment by alphaRGB** [comment]
> Thank for being interested in Ccl dialect and Mesh dialect.
> 
> If you use the ByteIR runtime, there is an NCCL backend for the nvidia GPUs. If you use other runtime or other hardware, you can lower ccl dialect to communication libraries based on the op semantics.
> 
> Mesh dialect in MLIR upstream is actually contributed by the ByteIR team. Meah dialect uses semantics of virtual or physical mesh network topology, which is often used in distributed training/inference for easy abstraction, while ccl dialect use physical rank to practically perform the real communication operations.
> 
> We originally introduce mesh dialect for supporting TF and pytorch training framework. However, due the current industrial training framework shifts more to pytoch, and pytorch natively lacks some support of mesh and distributed abstraction at the moment we released mesh dialect, the ByteIR team decided to extend PyTorch ecosystem first in order to link mesh to pytorch later and make the ecosystem more practical. The extension we built is called veScale, you can find in this link https://github.com/volcengine/vescale . Consequently, we postponed building mesh to ccl lowering and went to build veScale first. After veScale is solid, we will bridge ByteIR and veScale, and resume the lowering. After all, we need to have upstream use first, and then build a downstream tool. At the current stage, we haven't released the veScale version that can link ByteIR yet, but we will release it soon.

Great works ! Thanks for your reply about the roadmap.
