### ISSUE TITLE
[QUESTION] Hardcoding in torch frontend build script prevents local building

### ISSUE THREAD

**Issue by GithubXxz** [bytedance/byteir#483]
I follow build docs in torch frontend README.md, while I encounter some build issue causing by hardcoding 
For instances in /path/to/byteir/frontends/torch-frontend/scripts/envsetup.sh:15
![CleanShot 2024-11-11 at 13 07 54@2x](https://github.com/user-attachments/assets/a2055e89-6435-4814-bf71-d15580b643ea)
and in /path/to/byteir/frontends/torch-frontend/scripts/build.sh
![CleanShot 2024-11-11 at 13 09 13@2x](https://github.com/user-attachments/assets/aa03dd85-557e-4d4d-89fb-a2672f1e1b5e)
Can someone help address the hardcoding issues in the build script so that I can build and test ByteIR locally?

**Comment by qingyunqu** [comment]
Hi, firstly, you do not need to install `mhlo-tools`, you can comment out this line.
Secondly, if you use `frontends/torch-frontend/scripts/build.sh`, you do not need the prebuilt llvm.
Use `clang-11` because `torch-2.4.1` requires `gcc>8`, you can change it to any cxx compiler which could work.
There are many limits when we try building, hardcoding is a naive way to provide a successful compilation.

**Comment by GithubXxz** [comment]
> In debian or ubuntu system, you can use `apt install clang-11` to install clang.

yes I mean I am just a little confused why not just use clang instead of clang-11, clang may be softlink to clang-11 or some further clang version. Or is this project dependent on a specific version of Clang?

**Comment by liwenchangbdbz** [comment]
In industrial, most products are tested under setups only highly related to their production and/or development environment.
It doesn't mean the products only work in those setups, or specifically dependent on some functionality.
It simply means the products tested in those setups.
Think about this way. 
It is extremely hard to test all versions, considering there are some combinations across many versions of OS, compilers, dependencies, drivers, and hardware.
That is why we need opensource community.  

Feel free to test ByteIR in different environments. 
If you hit related issues or/and happen to have a solution, also feel free to send us a PR.   

I will close the issue, since your major questions got answered.
Feel free to open a question, if you have any further one.
